CREATE DATABASE IF NOT EXISTS Shop;
USE Shop;

CREATE TABLE IF NOT EXISTS Product (
idProduct INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(45) NOT NULL,
ipn INT NOT NULL,
description VARCHAR(255) NOT NULL,
amount INT NOT NULL DEFAULT	0,
id_schedule INT NOT NULL,
img VARCHAR(127) NOT NULL,
color VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS Ordering(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
idProduct INT DEFAULT NULL,
FOREIGN KEY (idProduct) REFERENCES Product (idProduct) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Profile (
id INT NOT NULL PRIMARY KEY, # Extract from Telegram
name VARCHAR(45) DEFAULT NULL,
surname VARCHAR(45) DEFAULT NULL,
patronymic VARCHAR(45) DEFAULT NULL,
country VARCHAR(45) DEFAULT NULL,
city VARCHAR(45) DEFAULT NULL,
post INT DEFAULT NULL,
delivery INT DEFAULT NULL,
card INT DEFAULT NULL,
idOrder INT NOT NULL DEFAULT 0,
FOREIGN KEY (idOrder) REFERENCES Ordering (id) ON UPDATE CASCADE
);
